# Generated by Django 4.1.5 on 2023-03-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stlast', models.CharField(max_length=256)),
                ('stname', models.CharField(max_length=256)),
                ('depcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentApp.department')),
            ],
            options={
                'db_table': 'tbl_student',
            },
        ),
    ]
