# Generated by Django 4.1.5 on 2023-04-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenhimApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bovog', models.CharField(max_length=256)),
                ('bname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('password_confirm', models.CharField(max_length=32)),
                ('tenhim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenhimApp.tenhim')),
            ],
        ),
    ]
