# Generated by Django 4.1.5 on 2023-04-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagshApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bagsh',
            table='bagsh',
        ),
    ]
