# Generated by Django 4.1.5 on 2023-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tbl_department',
            },
        ),
    ]
