# Generated by Django 4.1.5 on 2023-04-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_rename_file_path_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
