# Generated by Django 4.1.5 on 2023-04-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0003_remove_song_duration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
